site_name: CCDExplorer.io - Documentation
site_description: Documentation for CCDExplorer.io
site_author: CCDExplorer.io
site_url: https://docs.ccdexplorer.io

nav:
  - Home: index.md
  - Projects: 
    - Overview: projects/index.md
    - API: projects/api.md
    - Notification Bot: projects/bot.md
    - Site: projects/site.md
    - Timed services: 
      - Accounts: projects/timed_services/accounts.md
      - Transactions by Type/Contents: projects/timed_services/transactions_by_type_contents.md
      - Statistics Daily Holders: projects/timed_services/statistics_daily_holders.md
      - Statistics Daily Limits: projects/timed_services/statistics_daily_limits.md
      - Account Graphs: projects/timed_services/account_graph.md
      - Transactions by projects: projects/timed_services/transactions_by_projects.md
      - Unique Active Addresses: projects/timed_services/statistics_unique_addresses.md
      - Statistics Transaction Fees: projects/timed_services/statistics_fees.md
      - Realized Prices: projects/timed_services/statistics_realized_prices.md
    - Every Block:
      - Heartbeat: projects/every_block/heartbeat.md
      - Block Analyzer: projects/every_block/block_analyzer.md
      - Indexers: projects/every_block/indexers.md
      - Events and Impacted Addresses: projects/every_block/events_and_impacted.md
      - Token Accounting: projects/every_block/token_accounting.md
      - Metadata: projects/every_block/metadata.md
      - PLT: projects/every_block/plt.md
      - New Account Address: projects/every_block/new_address.md
      - New/Upgraded Contract: projects/every_block/new_contract.md
      - New/Upgraded Module: projects/every_block/new_module.md
    - Misc:
      - Concordium Recognized Projects: projects/projects.md
  - Entities:
    - Overview: entities/index.md
    - Block: entities/block.md
    - Transaction: entities/transaction.md
    - Account: entities/account.md
    - Module: entities/module.md
    - Token: entities/token.md
    - Community Labels: entities/community_labels.md
      
  - Components:
    - Celery: components/celery.md
    - CIS: components/cis.md
    - CNS: components/cns.md
    - Domain: components/domain.md
    - GRPC: components/grpc.md
    - MongoDB: components/mongodb.md
    - SchemaParser: components/schema-parser.md
    - Tooter: components/tooter.md
    - WasmDecoder: components/wasmdecoder.md
docs_dir: docs

markdown_extensions:
  - admonition  
  - toc:
      permalink: true

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          # Make your monorepo code importable for mkdocstrings/griffe:
          paths:
            - "."  # repo root; adjust if needed
          setup_commands:
            - "import os, sys; sys.path.insert(0, os.path.abspath('.'))"
          options:
            show_bases: false
            docstring_options:
              ignore_init_summary: true
            heading_level: 2
            inherited_members: true
            show_source: false
            summary: true

theme:
  name: material
  primary: deep purple
  palette:
    - media: "(prefers-color-scheme)"
      toggle: { icon: material/brightness-auto, name: Switch to light mode }
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: { icon: material/brightness-7, name: Switch to dark mode }
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: lime
      toggle: { icon: material/brightness-4, name: Switch to system pcomponents }